language: python
python: 3.7

install:
    - pip install -r requirements.txt

script:
    - python run.py
    - tar -czf outputs.tar.gz ./output
    
deploy:
    provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: 'outputs.tar.gz'